[package]
name = "Nothing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.27.5"
winapi = { version = "0.3.9", features = ["winuser","wincontypes","wincon"] }
rusty_password = "0.1.2"
# libc = { version = "0.2.138", features = ["geteuid"] }
colored = "^1.9"
base64 = "0.20.0"